### ISSUE TITLE
Alternative-energies.fr: mastondon doesn't send email

### ISSUE THREAD

**Issue by indykish** [megamsys/support#13]
### Description of your issue:
Logs doesn't appear reliably through mailgun after running mastondon.

### Expected behaviour

Should send email

### Actual behaviour

Didn't send an email.

### Steps to reproduce the issues

```
ssh root@163.172.180.239
```

[https://github.com/tootsuite/mastodon](https://github.com/tootsuite/mastodon)

[https://wogan.blog/2017/04/09/getting-started-with-mastodon/](https://wogan.blog/2017/04/09/getting-started-with-mastodon/)

Check logs

NOTE: If you are experiencing a deploy failure, please include:

-Link to the failed deployment. We'll use the administrator id to impersonate and debug.
- Any logs as per [troubleshooting](http://docs.megam.io/troubleshooting/)
- Upload screenshots if there is an error reported in the userinteface.

**Comment by indykish** [comment]
Here are the smtp settings as available in `/home/mastondon/.env.production`

```
SMTP_SERVER=smtp.mailgun.org
SMTP_PORT=587
SMTP_LOGIN=postmaster@mg.freelab.cc
SMTP_PASSWORD=xxxxxxnotshown
SMTP_FROM_ADDRESS=no-reply@freelab.cc

```

[The port 587 is `STARTTLS`  Reference](https://documentation.mailgun.com/user_manual.html#sending-via-smtp)

[Enable the following and check it out](https://documentation.mailgun.com/user_manual.html#tls-sending-connection-settings)
```
SMTP_DELIVERY_METHOD=smtp # delivery method can also be sendmail
SMTP_AUTH_METHOD=plain
SMTP_OPENSSL_VERIFY_MODE=peer
SMTP_ENABLE_STARTTLS_AUTO=true
```

**Comment by indykish** [comment]
Possibly

https://www.scaleway.com/faq/server/network/

**Comment by rajesh-rajagopal** [comment]
![image](https://cloud.githubusercontent.com/assets/18652643/25436486/fd783478-2ab0-11e7-9173-4a62499d33d5.png)

**Comment by indykish** [comment]
I can see `Net::OpenTimeout`. Port is blocked probably. Will let xavier know.

**Comment by rajesh-rajagopal** [comment]
Yes sir. I referred this link 
https://github.com/tootsuite/mastodon/issues/2435

https://github.com/tootsuite/mastodon/issues/2312

**Comment by rajesh-rajagopal** [comment]
Its fixed...
Solution,
Xavier opened the below ports. refer this pic.
![capture du 2017-04-29 09-44-27](https://cloud.githubusercontent.com/assets/18652643/25605073/fb152528-2f25-11e7-84bf-57265808a765.png)
