### ISSUE TITLE
demo.virtengine.com: VM upon launching  moves to POWEROFF state 

### ISSUE THREAD

**Issue by indykish** [megamsys/support#15]
### Description of your issue:
1. VM is automatically go for an poweroff state.

### Steps to reproduce the issues

NOTE: If you are experiencing a deploy failure, please include:

-Link to the failed deployment. We'll use the administrator id to impersonate and debug.
- Any logs as per [troubleshooting](http://docs.megam.io/troubleshooting/)
- Upload screenshots if there is an error reported in the userinteface.

**Comment by rajesh-rajagopal** [comment]
**Same issues** occur in **astimp server** also, 
But there we can use NFS storage server, VM can't deleted fully. Running VM differ from OpenNebula UI to virsh list (running VM).

**Fix for astimp server:**
Delete, destroyed VM that running on host internally using virsh command
(virsh destroy VM_Id)

**Comment by rajesh-rajagopal** [comment]
I found only 13 images is runnning on OpenNebula
but there are 21 images are running on background..

![image](https://cloud.githubusercontent.com/assets/18652643/25372047/689f6b14-29b1-11e7-83d1-805bc1c4f83f.png)
![image](https://cloud.githubusercontent.com/assets/18652643/25372063/79247be6-29b1-11e7-818f-2df53924dd63.png)
![image](https://cloud.githubusercontent.com/assets/18652643/25372081/8218b0c8-29b1-11e7-8a57-3a08d61c4d83.png)

so i deleted un used VM using virsh destroy command.

**Comment by rajesh-rajagopal** [comment]
I launched one images from http://demo.virtengine.com and check is everything ok

**Comment by indykish** [comment]
Yeah, those ghost VMs, we need a way to cleanup. Hopefully in 2.0 this will be done.

**Comment by rajesh-rajagopal** [comment]
This will be fixed on astimp server.

Delete the existing host and create new host
