### ISSUE TITLE
Demo.virtengine.com: VM is parked state.

### ISSUE THREAD

**Issue by indykish** [megamsys/support#19]
### Description of your issue:

Can you check this account: http://demo.virtengine.com/user/tk@gthost.com

VM Not Supposed to be parked, and app has 'error'

### NOTE:

If you are experiencing a deploy failure, please include:

- Paste the URL for the failed deployment. We'll use the administrator id to impersonate and debug.
- Upload screenshots if there is an error reported in the userinteface.

**Comment by rajesh-rajagopal** [comment]
Quota is not valid once user can launched a VM..

**steps to reproduce:-**
Launched a VM from purchased quota after that delete a VM then the quota is not shown in UI, when i launched a VM it shows **insufficient fund**

**Comment by rajesh-rajagopal** [comment]
refer https://github.com/megamsys/vertice/issues/434
