### ISSUE TITLE
Raid:Flavor order must be in ASC

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/support#2]
### Description of your issue:

Admin created the flavor but its not shown as ASC order while launching..

### Steps to reproduce the issues
Add flavor from virtengine admin panel

NOTE: If you are experiencing a deploy failure, please include:

-Link to the failed deployment. We'll use the administrator id to impersonate and debug.
- Any logs as per [troubleshooting](http://docs.megam.io/troubleshooting/)
- Upload screenshots if there is an error reported in the userinteface.

**Comment by rajesh-rajagopal** [comment]
Flavor records
name         | id                     | category            | cpu | created_at                      | disk | json_claz      | price                                                                                                                                                                                                                                                                                                                                                                   | properties | ram | regions         | status     | updated_at

 Raid35-POWER | FLV8130861935223401903 | ['VM', 'CONTAINER'] |  35 | 2017-04-25 06:02:39.000000+0000 | 2275 | Megam::Flavors |    ['{"key":"hdd_cost_hour","value":"0"}', '{"key":"hdd_cost_month","value":"0"}', '{"key":"ssd_cost_hour","value":"0.00006153846"}', '{"key":"ssd_cost_month","value":"100.8"}', '{"key":"cpu_cost_hour","value":"0.008"}', '{"key":"cpu_cost_month","value":"201.6"}', '{"key":"ram_cost_hour","value":"0.00133333333"}', '{"key":"ram_cost_month","value":"201.6"}'] |       null | 210 |    ['Chicago_VPS'] | inprogress | 2017-04-25 06:02:39.000000+0000

   Raid3-GAME | FLV6496827393820881415 | ['VM', 'CONTAINER'] |   3 | 2017-04-18 08:40:17.000000+0000 |  150 | Megam::Flavors |     ['{"key":"hdd_cost_hour","value":"0"}', '{"key":"hdd_cost_month","value":"0"}', '{"key":"ssd_cost_hour","value":"0.00013888888"}', '{"key":"ssd_cost_month","value":"15"}', '{"key":"cpu_cost_hour","value":"0.01388888888"}', '{"key":"cpu_cost_month","value":"30"}', '{"key":"ram_cost_hour","value":"0.00347222222"}', '{"key":"ram_cost_month","value":"30"}'] |       null |  12 | ['Strasbourg_VPS'] | inprogress | 2017-04-18 08:40:17.000000+0000

 Raid31-POWER | FLV5188583335459151465 | ['VM', 'CONTAINER'] |  31 | 2017-04-25 05:59:26.000000+0000 | 2015 | Megam::Flavors |  ['{"key":"hdd_cost_hour","value":"0"}', '{"key":"hdd_cost_month","value":"0"}', '{"key":"ssd_cost_hour","value":"0.00006153846"}', '{"key":"ssd_cost_month","value":"89.28"}', '{"key":"cpu_cost_hour","value":"0.008"}', '{"key":"cpu_cost_month","value":"178.56"}', '{"key":"ram_cost_hour","value":"0.00133333333"}', '{"key":"ram_cost_month","value":"178.56"}'] |       null | 186 |    ['Chicago_VPS'] | inprogress | 2017-04-25 05:59:26.000000+0000

**Comment by indykish** [comment]
Thanks Rajesh.

Fixed in https://github.com/megamsys/verticegateway/issues/597

**Comment by rajesh-rajagopal** [comment]
Okay sir.. I will update gateway in raid server and check it.

**Comment by rajesh-rajagopal** [comment]
Its fixed.
