### ISSUE TITLE
Demo.virtengine.com: Unable to proceed to step2 from the launcher.

### ISSUE THREAD

**Issue by indykish** [megamsys/support#20]
### Description of your issue:

I impersonated as `hello@virtengine.com`, and i am unable to proceed to step2.

### NOTE:

If you are experiencing a deploy failure, please include:

- Paste the URL for the failed deployment. We'll use the administrator id to impersonate and debug.

```
Impersonate as `hello@virtengine.com`

```
- Upload screenshots if there is an error reported in the userinteface.

![ss 2017-04-25 at 09 14 48](https://cloud.githubusercontent.com/assets/1402479/25382895/339a1894-29d7-11e7-9c01-95bf4b8f3284.png)

**Comment by rajesh-rajagopal** [comment]
**Issue:**
In backup table contains non-vm records. It means VM launched and user can take a backup then they delete the VM. But backup record it not deleted in database. 

**solution:** 
When i try to launch a VM, backup record exist in backup table that doesn't have assembly and assemblies table so i delete backup table records. now it works fine.
