### ISSUE TITLE
Astimp: Cassandra unstable to get records 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/support#23]
### Description of your issue:

Once i tried to get organizations record it gave 10 rows 
again i tried to get organizations record it gave 13 rows
after few seconds again it gave 10 rows

### NOTE:

If you are experiencing a deploy failure, please include:

- Paste the URL for the failed deployment. We'll use the administrator id to impersonate and debug.
- Upload screenshots if there is an error reported in the userinteface.

**Comment by rajesh-rajagopal** [comment]
Now, we cleaned cassandra database try it now

**Comment by indykish** [comment]
Don't worry we'll get rid of cassandra in 2.0

**Comment by indykish** [comment]
For now let me install `scylla` in `apdb.megam.io` to see if its better on memory.
