### ISSUE TITLE
megam.cloud Unable to get to Step 2

### ISSUE THREAD

**Issue by indykish** [megamsys/support#29]
### Description of your issue:

1. I clicked on  `Create VM` in `megam.cloud`
2. Selected a flavor.
3. Clicked `Next`

The spinner just spins, can't get to `Step 2` ?

Can we test please  ? 

### NOTE:

If you are experiencing a deploy failure, please include:

- Paste the URL for the failed deployment. We'll use the administrator id to impersonate and debug.
- Upload screenshots if there is an error reported in the userinteface.

**Comment by rajesh-rajagopal** [comment]
Its fixed..
