### ISSUE TITLE
Astimp: Admin shall update the flavor

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/support#3]
### Description of your issue:
 Admin cannot change the flavor
### Steps to reproduce the issues
can not change the value in the flavor after creating.
NOTE: If you are experiencing a deploy failure, please include:

-Link to the failed deployment. We'll use the administrator id to impersonate and debug.
- Any logs as per [troubleshooting](http://docs.megam.io/troubleshooting/)
- Upload screenshots if there is an error reported in the userinteface.

**Comment by rajesh-rajagopal** [comment]
Its fixed.. we can update/delete the flavor from admin panel
