### ISSUE TITLE
Astimp:admin have the possibility to add new user manualy without WHMCS 

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/support#6]
### Description of your issue:
possibility to add new user manualy without WHMCS 
### Steps to reproduce the issues
admin dashboard-i need the possibility to add new user manualy without WHMCS ( secret users/user that dont need to pay like friends, my workers...)
NOTE: If you are experiencing a deploy failure, please include:

-Link to the failed deployment. We'll use the administrator id to impersonate and debug.
- Any logs as per [troubleshooting](http://docs.megam.io/troubleshooting/)
- Upload screenshots if there is an error reported in the userinteface.

**Comment by rajesh-rajagopal** [comment]
Its fixed..
