### ISSUE TITLE
Astimp:service suspension

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/support#9]
### Description of your issue:
To suspend the  unpaid service 
### Steps to reproduce the issues
service suspension ( by unpaid ) - not the account only the unpaid service
NOTE: If you are experiencing a deploy failure, please include:

-Link to the failed deployment. We'll use the administrator id to impersonate and debug.
- Any logs as per [troubleshooting](http://docs.megam.io/troubleshooting/)
- Upload screenshots if there is an error reported in the userinteface.

**Comment by rajesh-rajagopal** [comment]
its under testing..
